name: Run Unit Tests

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install Dependencies
        run: npm i

      - name: Unit testing
        run: |
          npm run test
